deploy-master:
    stage: deploy
    image: alpine:latest
    before_script:
        #### Login to Deployment server
        - apk update; apk add --no-cache openssh-client
        - eval "$(ssh-agent -s)"
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "${PRIVATE_KEY_SERVER_DEPLOY}" > ~/.ssh/id_sireno
        - chmod 400 ~/.ssh/id_sireno
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config
    script:
        - ssh-add ~/.ssh/id_sireno
        - ssh-keyscan -H "${HOST_SERVER_DEPLOY}" > ~/.ssh/known_hosts
        - ssh -p"${PORT_SERVER_DEPLOY}" "${USER_SERVER_DEPLOY}"@"${HOST_SERVER_DEPLOY}" /home/tester/./pull_sireno.sh